# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/data_sheet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1086, 757)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_frame.sizePolicy().hasHeightForWidth())
        self.toolbar_frame.setSizePolicy(sizePolicy)
        self.toolbar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbar_frame.setObjectName("toolbar_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbar_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.toolbar_frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_view = QtWidgets.QComboBox(self.toolbar_frame)
        self.comboBox_view.setObjectName("comboBox_view")
        self.horizontalLayout.addWidget(self.comboBox_view)
        self.line = QtWidgets.QFrame(self.toolbar_frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton_2 = QtWidgets.QPushButton(self.toolbar_frame)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.button_new_entry = QtWidgets.QPushButton(self.toolbar_frame)
        self.button_new_entry.setObjectName("button_new_entry")
        self.horizontalLayout.addWidget(self.button_new_entry)
        self.button_edit_entry = QtWidgets.QPushButton(self.toolbar_frame)
        self.button_edit_entry.setObjectName("button_edit_entry")
        self.horizontalLayout.addWidget(self.button_edit_entry)
        self.button_delete_entry = QtWidgets.QPushButton(self.toolbar_frame)
        self.button_delete_entry.setObjectName("button_delete_entry")
        self.horizontalLayout.addWidget(self.button_delete_entry)
        self.button_edit_form = QtWidgets.QPushButton(self.toolbar_frame)
        self.button_edit_form.setObjectName("button_edit_form")
        self.horizontalLayout.addWidget(self.button_edit_form)
        self.button_edit_plugin = QtWidgets.QPushButton(self.toolbar_frame)
        self.button_edit_plugin.setObjectName("button_edit_plugin")
        self.horizontalLayout.addWidget(self.button_edit_plugin)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.toolbar_frame)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableView = FreezeTableWidget(self.splitter)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setObjectName("tableView")
        self.cell_value_frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_value_frame.sizePolicy().hasHeightForWidth())
        self.cell_value_frame.setSizePolicy(sizePolicy)
        self.cell_value_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cell_value_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cell_value_frame.setObjectName("cell_value_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cell_value_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cell_value = QtWidgets.QTextBrowser(self.cell_value_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_value.sizePolicy().hasHeightForWidth())
        self.cell_value.setSizePolicy(sizePolicy)
        self.cell_value.setObjectName("cell_value")
        self.verticalLayout_2.addWidget(self.cell_value)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "View:"))
        self.pushButton_2.setText(_translate("Form", "Find"))
        self.button_new_entry.setText(_translate("Form", "New entry"))
        self.button_edit_entry.setText(_translate("Form", "Edit entry"))
        self.button_delete_entry.setText(_translate("Form", "Delete entry"))
        self.button_edit_form.setText(_translate("Form", "Form"))
        self.button_edit_plugin.setText(_translate("Form", "Plugin"))
from widgets import FreezeTableWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
