# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/item_choice_radio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 96)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_key = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_key.sizePolicy().hasHeightForWidth())
        self.label_key.setSizePolicy(sizePolicy)
        self.label_key.setObjectName("label_key")
        self.verticalLayout.addWidget(self.label_key)
        self.radio_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_frame.sizePolicy().hasHeightForWidth())
        self.radio_frame.setSizePolicy(sizePolicy)
        self.radio_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.radio_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.radio_frame.setObjectName("radio_frame")
        self.radio_layout = QtWidgets.QVBoxLayout(self.radio_frame)
        self.radio_layout.setContentsMargins(0, 0, 0, 0)
        self.radio_layout.setSpacing(2)
        self.radio_layout.setObjectName("radio_layout")
        self.verticalLayout.addWidget(self.radio_frame)
        self.radio_button_other_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_button_other_frame.sizePolicy().hasHeightForWidth())
        self.radio_button_other_frame.setSizePolicy(sizePolicy)
        self.radio_button_other_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.radio_button_other_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.radio_button_other_frame.setObjectName("radio_button_other_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.radio_button_other_frame)
        self.horizontalLayout.setContentsMargins(10, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_button_other = QtWidgets.QRadioButton(self.radio_button_other_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_button_other.sizePolicy().hasHeightForWidth())
        self.radio_button_other.setSizePolicy(sizePolicy)
        self.radio_button_other.setText("")
        self.radio_button_other.setObjectName("radio_button_other")
        self.horizontalLayout.addWidget(self.radio_button_other)
        self.other_field = QtWidgets.QLineEdit(self.radio_button_other_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_field.sizePolicy().hasHeightForWidth())
        self.other_field.setSizePolicy(sizePolicy)
        self.other_field.setObjectName("other_field")
        self.horizontalLayout.addWidget(self.other_field)
        self.verticalLayout.addWidget(self.radio_button_other_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_key.setText(_translate("Form", "Key"))
        self.other_field.setPlaceholderText(_translate("Form", "Other"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
