# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/item_datetime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 66)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.datetime_frame = QtWidgets.QFrame(Form)
        self.datetime_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datetime_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.datetime_frame.setObjectName("datetime_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.datetime_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.datetime_field = QtWidgets.QDateEdit(self.datetime_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datetime_field.sizePolicy().hasHeightForWidth())
        self.datetime_field.setSizePolicy(sizePolicy)
        self.datetime_field.setCalendarPopup(True)
        self.datetime_field.setObjectName("datetime_field")
        self.horizontalLayout.addWidget(self.datetime_field)
        self.frame_hour = QtWidgets.QFrame(self.datetime_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_hour.sizePolicy().hasHeightForWidth())
        self.frame_hour.setSizePolicy(sizePolicy)
        self.frame_hour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hour.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hour.setObjectName("frame_hour")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_hour)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hour_field = QtWidgets.QLineEdit(self.frame_hour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hour_field.sizePolicy().hasHeightForWidth())
        self.hour_field.setSizePolicy(sizePolicy)
        self.hour_field.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hour_field.setMaxLength(2)
        self.hour_field.setFrame(True)
        self.hour_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hour_field.setObjectName("hour_field")
        self.horizontalLayout_2.addWidget(self.hour_field)
        self.label = QtWidgets.QLabel(self.frame_hour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.minute_field = QtWidgets.QLineEdit(self.frame_hour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minute_field.sizePolicy().hasHeightForWidth())
        self.minute_field.setSizePolicy(sizePolicy)
        self.minute_field.setMaximumSize(QtCore.QSize(50, 16777215))
        self.minute_field.setMaxLength(2)
        self.minute_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minute_field.setObjectName("minute_field")
        self.horizontalLayout_2.addWidget(self.minute_field)
        self.horizontalLayout.addWidget(self.frame_hour)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.datetime_frame)
        self.label_key = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_key.sizePolicy().hasHeightForWidth())
        self.label_key.setSizePolicy(sizePolicy)
        self.label_key.setObjectName("label_key")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_key)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hour_field.setText(_translate("Form", "11"))
        self.label.setText(_translate("Form", "h"))
        self.label_key.setText(_translate("Form", "Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
